services:
  - type: web
    name: document-insight-backend
    runtime: python
    region: oregon
    plan: starter
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ENVIRONMENT
        value: production
      - key: EMBEDDING_PROVIDER
        value: local_dummy
      - key: ANSWER_PROVIDER
        value: local
      - key: LOCAL_DUMMY_DIMENSION
        value: 384
      - key: VECTORSTORE_DIR
        value: /var/data/vectorstore
      - key: ALLOWED_ORIGINS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: OPENAI_ANSWER_MODEL
        value: ""
    disk:
      name: vectorstore
      mountPath: /var/data
      sizeGB: 1

  - type: web
    name: document-insight-frontend
    runtime: python
    region: oregon
    plan: starter
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python -m streamlit run frontend/streamlit_app.py --server.address 0.0.0.0 --server.port $PORT --browser.gatherUsageStats false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ENVIRONMENT
        value: production
      - key: BACKEND_BASE_URL
        sync: false
